services:
  counter:
    container_name: counter_app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  app:
